"""base model abstraction

Revision ID: 4fe4385d8e3c
Revises: 12ec426d3369
Create Date: 2024-03-23 09:19:28.297194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe4385d8e3c'
down_revision: Union[str, None] = '12ec426d3369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_recipient', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('email_recipient', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('email_recipient', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('emails', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('emails', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('emails', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'deleted_at')
    op.drop_column('emails', 'updated_at')
    op.drop_column('emails', 'created_at')
    op.drop_column('email_recipient', 'deleted_at')
    op.drop_column('email_recipient', 'updated_at')
    op.drop_column('email_recipient', 'created_at')
    # ### end Alembic commands ###
